### ISSUE TITLE
Missing picture in news post

### ISSUE THREAD

**Issue by kate-holdener** [oss-slu/oss-slu.github.io#9]
The "News" tab contains a post linking to a SLU article. It looks like there is a place to show a picture of the post author. However, the picture is not showing up. Screenshot below shows the issues (look to the left of text "Daniel Shown")

<img width="1601" alt="Screen Shot 2023-04-26 at 2 43 02 PM" src="https://user-images.githubusercontent.com/42073871/234685655-77d77f7d-ecd8-41d8-8804-9c808d0ca23a.png">

**Comment by kungfuchicken** [comment]
resolved
